# Site settings
author: Temitope Elodimuor
title: Full stack Mom
header-img: img/home-bg.png
email: ruth_olukunle@yahoo.com
copyright_name: Temitope Elodimuor
description: > # this means to ignore newlines until "baseurl:"
  Learning to code as a mom
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  ELTemi

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
